### ISSUE TITLE
dub build fails

### ISSUE THREAD

**Issue by btbytes** [MartinNowak/serve#1]
```
$ dub build serve
...

Error executing command build: Failed to download http://code.dlang.org/packages/libevent/2.0.1%252B2.0.16.zip: 404 Not Found
```

This is on Mac OS X - Yosemite.

**Comment by MartinNowak** [comment]
Thanks for reporting, it's a duplicate of https://github.com/D-Programming-Language/dub/issues/411. Please update your dub version to v0.9.22 or try the release candidate for v0.9.23.
http://code.dlang.org/download

Feel free to close the bug if that solves your problem.

**Comment by btbytes** [comment]
updating dub to v0.9.22 fixed this issue.

Thanks!
