### ISSUE TITLE
Support HTTPS protocol

### ISSUE THREAD

**Issue by aberba** [MartinNowak/serve#4]
Some modern web APIs only work when https is enabled. Any dummy SSL cert will do the trick.

**Comment by MartinNowak** [comment]
I wouldn't suggest to directly put this on the internet, rather use an established server like Nginx or HAProxy for TLS termination.
Anyhow added a https build config `dub build -c https` that supports a `-https-crt=path/to/combined_crt_and_key.pem` argument and will serve over TLS.
